// src/views/BirthdayResult.vue
<script setup lang="ts">
import { ref, onMounted, watch, computed } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { fetchNextBirthday } from '../lib/api'
import { confetti } from '../lib/confetti'
import { formatDate, isSameDate } from '../lib/date'
import { type NextBirthday } from '../lib/birthday'
import AppButton from '../components/AppButton.vue'

const isLoading = ref(true)
const birthdays = ref<NextBirthday[]>([])
const isToday = ref(false)
const isShowingAll = ref(false)

const route = useRoute()
const router = useRouter()

const code = computed(() => route.params.code as string)

const updatePerson = async (code: string) => {
  if (!code) {
    router.push('/')
    return
  }
  const result = await fetchNextBirthday(code)
  isLoading.value = false

  if (!result) {
    return
  }

  birthdays.value = result
  const today = isSameDate(new Date(result[0]?.next_birthday))
  isToday.value = today
  if (today) {
    await confetti()
  }
}

watch(code, (newCode) => {
  if (typeof newCode === 'string') {
    isLoading.value = true
    updatePerson(newCode)
  }
})

const showAll = async () => {
  isLoading.value = true
  const result = await fetchNextBirthday(code.value!, true)
  if (result) birthdays.value = result
  isLoading.value = false
  isShowingAll.value = true
}

onMounted(() => {
  if (typeof code.value === 'string') {
    isLoading.value = true
    updatePerson(code.value)
  }
})
</script>

<template>
  <div v-if="isLoading">Laden...</div>
  <div v-else-if="birthdays.length" class="text-center">
    <p v-for="birthday in birthdays" :key="birthday.name">
      <span>
        {{ birthday.name }} is op {{ formatDate(birthday.next_birthday) }} jarig en word dan
        {{ birthday.age }}!
      </span>
      &nbsp;
      <a
        v-if="birthday.website"
        class="text-xs"
        :href="birthday.website.toString()"
        target="_blank"
        rel="noreferrer"
      >
        Bekijk hier mijn verlanglijstje.
      </a>
    </p>
    <p v-if="isToday" class="text-xl">
      🎉🥳&nbsp;
      <button class="rainbow-text" type="button" @click="confetti">
        En dat is vandaag! Van harte gefeliciteerd!
      </button>
      &nbsp;🥳🎉
    </p>
    <AppButton v-if="!isShowingAll" class="mt-4" @click="showAll">
      Bekijk welke verjaardagen er nog meer aan komen
    </AppButton>
  </div>
  <div v-else>Niemand gevonden</div>
</template>

// client/src/routes/BirthdayResult.tsx
import React, { useCallback, useEffect, useState } from 'react'
import { fetchNextBirthday, NextBirthday } from '../lib/api'
import { confetti } from '../lib/confetti'
import { formatDate, isSameDate } from '../lib/date'
import { useNavigate, useParams } from 'react-router-dom'
import { Button } from '../app/Button'

type Params = {
  code: string
}
export const BirthDayResult: React.FC = () => {
  const [isLoading, setLoading] = useState(true)
  const [birthdays, setBirthdays] = useState<NextBirthday[]>([])
  const [isToday, setToday] = useState(false)
  const [isShowingAll, setShowingAll] = useState(false)
  const { code } = useParams<Params>()
  const navigate = useNavigate()

  const updatePerson = async (code: string) => {
    if (!code) {
      navigate('/')
      return
    }
    const result = await fetchNextBirthday(code)
    setLoading(false)

    if (!result) {
      return
    }

    setBirthdays(result)
    const today = isSameDate(new Date(result[0]?.nextBirthday))
    setToday(today)
    if (today) {
      await confetti()
    }
  }

  useEffect(() => {
    if (typeof code === 'string') {
      setLoading(true)
      void updatePerson(code)
    }
  }, [code])

  const showAll = useCallback(async () => {
    setLoading(true)
    const result = await fetchNextBirthday(code!, true)
    if (result) setBirthdays(result)
    setLoading(false)
    setShowingAll(true)
  }, [code])

  if (isLoading) {
    return <div>Laden...</div>
  }

  return birthdays ? (
    <div className="text-center">
      {birthdays.map((birthday) => (
        <p key={birthday.name}>
          {birthday.name} is op {formatDate(birthday.nextBirthday)} jarig en word dan {birthday.age}
          !
        </p>
      ))}
      {isToday && (
        <p className="text-xl">
          🎉🥳&nbsp;
          <button className="rainbow-text" type="button" onClick={() => confetti()}>
            En dat is vandaag! Van harte gefeliciteerd!
          </button>
          &nbsp;🥳🎉
        </p>
      )}
      {!isShowingAll && (
        <Button className="mt-4" onClick={showAll}>
          Bekijk welke verjaardagen er nog meer aan komen
        </Button>
      )}
    </div>
  ) : (
    <div>Niemand gevonden</div>
  )
}
